/* Configure API_BASE in config.js. It defaults to /api when hosted with server/. */
const API_BASE = (window.ERECTION_PLANNER_API_BASE || "/api").replace(/\/$/, "");
let workspace, projectId, activePlan, accessToken;
const el = (id) => document.getElementById(id);
function status(message, kind = "") { const node = el("statusMessage"); node.textContent = message; node.className = kind; }
function escapeHtml(value) { return String(value ?? "").replace(/[&<>\"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c])); }
async function token() { if (accessToken) return accessToken; const result = await workspace.extension.requestPermission("accesstoken"); accessToken = typeof result === "string" ? result : result?.accessToken || result?.token; return accessToken; }
async function api(path, options = {}) { const headers = new Headers(options.headers); headers.set("Content-Type", "application/json"); const t = await token(); if (t) headers.set("Authorization", `Bearer ${t}`); const response = await fetch(`${API_BASE}${path}`, {...options, headers}); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || `Request failed (${response.status})`); return data; }
async function loadContractor() { const [contractors, assignment] = await Promise.all([api("/contractors"), api(`/projects/${encodeURIComponent(projectId)}/contractor`)]); const select = el("contractorSelect"); select.replaceChildren(new Option("Select contractor…", ""), ...contractors.map(c => new Option(c.ContractorName, c.ContractorId))); const locked = Boolean(assignment?.IsLocked); el("contractorLocked").hidden = !locked; el("contractorEditor").hidden = locked; if (locked) { el("lockedContractorName").textContent = `🔒 ${assignment.ContractorName}`; el("lockedContractorMeta").textContent = `Locked ${new Date(assignment.AssignedDate).toLocaleString()}`; } }
async function saveContractor() { const contractorId = el("contractorSelect").value; if (!contractorId) return; if (!confirm("Save and permanently lock this contractor for the project?")) return; await api(`/projects/${encodeURIComponent(projectId)}/contractor`, {method:"POST", body:JSON.stringify({contractorId})}); await loadContractor(); status("Contractor saved and locked.", "success"); }
async function loadPlans() { const plans = await api(`/projects/${encodeURIComponent(projectId)}/plans`); const list = el("planList"); list.replaceChildren(...plans.map(plan => { const button = document.createElement("button"); button.className = activePlan?.PlanId === plan.PlanId ? "active" : ""; button.innerHTML = `<span>Plan ${plan.PlanNumber}${plan.PlanName ? ` — ${escapeHtml(plan.PlanName)}` : ""}</span><span>›</span>`; button.onclick = () => choosePlan(plan); const li = document.createElement("li"); li.append(button); return li; })); }
async function createPlan() { const planNumber = Number(el("newPlanNumber").value); const planName = el("newPlanName").value.trim(); if (!Number.isInteger(planNumber) || planNumber < 1) throw new Error("Enter a positive whole plan number."); await api(`/projects/${encodeURIComponent(projectId)}/plans`, {method:"POST",body:JSON.stringify({planNumber,planName})}); el("newPlanNumber").value = ""; el("newPlanName").value = ""; await loadPlans(); status(`Plan ${planNumber} created.`, "success"); }
async function choosePlan(plan) { activePlan = plan; el("assemblyCard").hidden = false; el("activePlanLabel").textContent = `Plan ${plan.PlanNumber}`; await Promise.all([loadPlans(), loadAssemblies()]); }
async function loadAssemblies() { const rows = await api(`/plans/${activePlan.PlanId}/assemblies`); const body = el("assemblyTableBody"); body.replaceChildren(...rows.map(row => { const tr = document.createElement("tr"); tr.innerHTML = `<td>${row.SequenceCode}</td><td>${escapeHtml(row.AssemblyName || row.AssemblyGuid)}</td><td>${escapeHtml(row.AssemblyGuid)}</td>`; return tr; })); el("assemblyEmpty").hidden = rows.length > 0; }
function propertyValue(item, names) { const flat = (item.properties || []).flatMap(set => set.properties || []); const found = flat.find(p => names.includes(String(p.name || "").toLowerCase())); return found?.value == null ? "" : String(found.value); }
async function addSelection() { if (!activePlan) return; const selection = await workspace.viewer.getSelection(); if (!selection?.length) throw new Error("Select one or more assemblies in the 3D Viewer first."); const assemblies = []; for (const group of selection) { const props = await workspace.viewer.getObjectProperties(group.modelId, group.objectRuntimeIds); props.forEach((item, i) => { const runtimeId = group.objectRuntimeIds[i]; const guid = propertyValue(item,["globalid","ifcguid","guid"]) || `${group.modelId}:${runtimeId}`; const name = propertyValue(item,["assembly mark","assembly","mark","name"]) || item.name || item.class || guid; assemblies.push({modelId:group.modelId,guid,name}); }); } const result = await api(`/plans/${activePlan.PlanId}/assemblies`, {method:"POST",body:JSON.stringify({assemblies})}); await loadAssemblies(); status(result.inserted.length ? `${result.inserted.length} assembly(s) added.` : "Those assemblies are already in this plan.", "success"); }
async function init() { try { workspace = await TrimbleConnectWorkspace.connect(window.parent, () => {}, 30000); const project = await workspace.project.getProject(); projectId = project.id; el("projectName").textContent = project.name || projectId; el("contractorSelect").onchange = e => el("saveContractorBtn").disabled = !e.target.value; el("saveContractorBtn").onclick = () => run(saveContractor); el("createPlanBtn").onclick = () => run(createPlan); el("addSelectionBtn").onclick = () => run(addSelection); await Promise.all([loadContractor(),loadPlans()]); status("Ready. Select a plan, then select assemblies in the 3D Viewer.", "success"); } catch (error) { console.error(error); status(error.message || "Unable to connect to Trimble Connect.", "error"); } }
async function run(action) { try { await action(); } catch (error) { console.error(error); status(error.message || "Operation failed.", "error"); } }
init();
